<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/1
 * Time: 16:16
 */

namespace Admin\Controller;
use Admin\Controller\ComController;
class AppOpenController extends ComController {

	public function _map()
	{
		return parent::_map(); // TODO: Change the autogenerated stub
	}


	/**
	 * 主页方法
	 * 显示APP名称 APP对应的定时设置
	 */
	public function index()
	{
		$map = $this->_map();
		$field = "zxt_appopen_name.id,zxt_hotel.hotelname,appname,GROUP_CONCAT(zxt_appopen_set.date,' ',zxt_appopen_set.start_time,'--',zxt_appopen_set.end_time,',' SEPARATOR '\n' ) as settime";
		$list = D('appopen_name')->where($map)
								 ->join('left join zxt_appopen_set on zxt_appopen_name.id=zxt_appopen_set.applistid')
								 ->join('left join zxt_hotel on zxt_appopen_name.hid=zxt_hotel.hid')
								 ->field($field)
						         ->select();
		$this -> assign("list",$list);
		$this -> display();
	}

	public function addappname(){
		$hid_condition = $this->isHotelMenber();
		var_dump($hid_condition);
	}
}